# Generated by Django 5.1.1 on 2024-10-14 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroPartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('id_catalano', models.CharField(max_length=250)),
                ('grupo', models.CharField(blank=True, max_length=250, null=True)),
                ('medida_cub', models.CharField(blank=True, max_length=250, null=True)),
                ('espesor_mm', models.CharField(blank=True, max_length=250, null=True)),
                ('dientes', models.IntegerField(blank=True, null=True)),
                ('rad_mm', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('cadena', models.CharField(blank=True, max_length=250, null=True)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_exterior', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_interior', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_rodillo', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_agujero_x_diametro_agujero', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_estrias_x_tipo_rosca', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_estrias_x_espesor_estrias', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.ImageField(upload_to='agro_imagenes')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotoPartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('id_catalano', models.CharField(max_length=250)),
                ('articulo', models.CharField(blank=True, max_length=250, null=True)),
                ('grupo', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo_marca', models.CharField(blank=True, max_length=250, null=True)),
                ('paso_de_la_cadena', models.CharField(blank=True, max_length=250, null=True)),
                ('dientes', models.IntegerField(blank=True, null=True)),
                ('compatible', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('cadena', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_original', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_exterior', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_interior', models.CharField(blank=True, max_length=250, null=True)),
                ('diametro_rodillo', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_agujero_x_diametro_agujero', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_estrias_x_tipo_rosca', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad_estrias_x_espesor_estrias', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.ImageField(upload_to='moto_imagenes')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('puntos_moto', models.IntegerField()),
                ('puntos_agro', models.IntegerField()),
                ('cuit', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('rubro', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
