# Generated by Django 5.1.3 on 2025-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0002_rename_agropartes_agroparte_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroparte',
            name='imagen',
            field=models.ImageField(upload_to='static/imagenes/agropartes'),
        ),
        migrations.AlterField(
            model_name='motoparte',
            name='imagen',
            field=models.ImageField(upload_to='static/imagenes/motopartes'),
        ),
    ]
