# Generated by Django 5.1.3 on 2025-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0004_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
