# Generated by Django 5.1.3 on 2025-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0005_premio_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='imagen',
            field=models.ImageField(upload_to='staticfiles/imagenes/premios'),
        ),
    ]
