# Generated by Django 5.1.3 on 2025-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0007_alter_premio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroparte',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/agropartes'),
        ),
        migrations.AlterField(
            model_name='motoparte',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/motopartes'),
        ),
    ]
