# Generated by Django 5.1.3 on 2025-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0008_alter_agroparte_imagen_alter_motoparte_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='puntos_agro',
            new_name='puntos',
        ),
        migrations.RenameField(
            model_name='premio',
            old_name='puntos',
            new_name='puntos_agroparte',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='puntos_moto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Agro', 'Agro'), ('Moto', 'Moto')], default='Moto', max_length=4),
        ),
        migrations.AddField(
            model_name='premio',
            name='puntos_motoparte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
