# Generated by Django 5.1.3 on 2025-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0009_rename_puntos_agro_cliente_puntos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_catalano',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
