# Generated by Django 5.1.3 on 2025-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0010_cliente_id_catalano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('orden', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='imagenes/catalogo')),
                ('archivo', models.FileField(upload_to='imagenes/catalogos/archivos')),
            ],
        ),
        migrations.AlterField(
            model_name='agroparte',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='motoparte',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='premio',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
