# Generated by Django 5.1.3 on 2025-04-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanoBackend', '0011_catalogo_alter_agroparte_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='imagen',
        ),
    ]
